# Dummy Variable Work on A Dataset

In [8]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("../insurance.csv")

In [6]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [9]:
df.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [11]:
df.info() #No missing Values in the Data set

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
age         1338 non-null int64
sex         1338 non-null object
bmi         1338 non-null float64
children    1338 non-null int64
smoker      1338 non-null object
region      1338 non-null object
charges     1338 non-null float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.2+ KB


## Linear Regression on The data set

In [15]:
df.head(6)

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520
5   31  female  25.740         0     no  southeast   3756.62160

In [16]:
X = df.age # data to regress

In [270]:
print(X.head())

   age     bmi  children  region
0   19  27.900         0       3
1   18  33.770         1       2
2   28  33.000         3       2
3   33  22.705         0       1
4   32  28.880         0       1


In [24]:
y=df["age"] #target 

In [271]:
y.head()

0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: charges, dtype: float64

## USing Dummy Variables

In [44]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [47]:
# converting sex to dummy
dummies_sex=pd.get_dummies(df.sex)

In [49]:
dummies_sex.head()

female  male
0       1     0
1       0     1
2       0     1
3       0     1
4       0     1

In [63]:
merged_sex = pd.concat([df,dummies_sex],axis=1)

In [65]:
merged_sex.head()

age     sex     bmi  children smoker     region      charges  female  male
0   19  female  27.900         0    yes  southwest  16884.92400       1     0
1   18    male  33.770         1     no  southeast   1725.55230       0     1
2   28    male  33.000         3     no  southeast   4449.46200       0     1
3   33    male  22.705         0     no  northwest  21984.47061       0     1
4   32    male  28.880         0     no  northwest   3866.85520       0     1

In [71]:
final_sex_male = merged_sex.drop(["male","sex"],axis = 1)

In [72]:
final_sex_male.head()

age     bmi  children smoker     region      charges  female
0   19  27.900         0    yes  southwest  16884.92400       1
1   18  33.770         1     no  southeast   1725.55230       0
2   28  33.000         3     no  southeast   4449.46200       0
3   33  22.705         0     no  northwest  21984.47061       0
4   32  28.880         0     no  northwest   3866.85520       0

In [117]:
final_sex_female = merged_sex.drop(["female","sex","smoker"],axis = 1)

In [118]:
final_sex_female.head()

age     bmi  children     region      charges  male
0   19  27.900         0  southwest  16884.92400     0
1   18  33.770         1  southeast   1725.55230     1
2   28  33.000         3  southeast   4449.46200     1
3   33  22.705         0  northwest  21984.47061     1
4   32  28.880         0  northwest   3866.85520     1

## Transforming Region to Dummy VAriables

In [119]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [120]:
region_dummy=pd.get_dummies(df.region)

In [80]:
region_dummy.head()

northeast  northwest  southeast  southwest
0          0          0          0          1
1          0          0          1          0
2          0          0          1          0
3          0          1          0          0
4          0          1          0          0

In [86]:
merged_dum_region=pd.concat([df,region_dummy],axis = 1)

In [87]:
merged_dum_region.head()

age     sex     bmi  children smoker     region      charges  northeast  \
0   19  female  27.900         0    yes  southwest  16884.92400          0   
1   18    male  33.770         1     no  southeast   1725.55230          0   
2   28    male  33.000         3     no  southeast   4449.46200          0   
3   33    male  22.705         0     no  northwest  21984.47061          0   
4   32    male  28.880         0     no  northwest   3866.85520          0   

   northwest  southeast  southwest  
0          0          0          1  
1          0          1          0  
2          0          1          0  
3          1          0          0  
4          1          0          0

In [192]:
final_region_merge = merged_dum_region.drop(["southeast","region"], axis =1)

In [193]:
final_region_merge.head()

age     sex     bmi  children smoker      charges  northeast  northwest  \
0   19  female  27.900         0    yes  16884.92400          0          0   
1   18    male  33.770         1     no   1725.55230          0          0   
2   28    male  33.000         3     no   4449.46200          0          0   
3   33    male  22.705         0     no  21984.47061          0          1   
4   32    male  28.880         0     no   3866.85520          0          1   

   southwest  
0          1  
1          0  
2          0  
3          0  
4          0

### Transforming Smokers to Dummy Variables

In [124]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [127]:
smoker_dummy=pd.get_dummies(df.smoker)

In [128]:
smoker_dummy.head()

no  yes
0   0    1
1   1    0
2   1    0
3   1    0
4   1    0

In [130]:
merged_smoker_dummy=pd.concat([df,smoker_dummy],axis=1)

In [131]:
merged_smoker_dummy.head()

age     sex     bmi  children smoker     region      charges  no  yes
0   19  female  27.900         0    yes  southwest  16884.92400   0    1
1   18    male  33.770         1     no  southeast   1725.55230   1    0
2   28    male  33.000         3     no  southeast   4449.46200   1    0
3   33    male  22.705         0     no  northwest  21984.47061   1    0
4   32    male  28.880         0     no  northwest   3866.85520   1    0

In [136]:
final_smokers_yes=merged_smoker_dummy.drop(["smoker","yes"],axis=1)

In [137]:
final_smokers_yes.head()

age     sex     bmi  children     region      charges  no
0   19  female  27.900         0  southwest  16884.92400   0
1   18    male  33.770         1  southeast   1725.55230   1
2   28    male  33.000         3  southeast   4449.46200   1
3   33    male  22.705         0  northwest  21984.47061   1
4   32    male  28.880         0  northwest   3866.85520   1

In [139]:
final_smokers_no=merged_smoker_dummy.drop(["smoker","no"],axis=1)

In [141]:
final_smokers_no.head()

age     sex     bmi  children     region      charges  yes
0   19  female  27.900         0  southwest  16884.92400    1
1   18    male  33.770         1  southeast   1725.55230    0
2   28    male  33.000         3  southeast   4449.46200    0
3   33    male  22.705         0  northwest  21984.47061    0
4   32    male  28.880         0  northwest   3866.85520    0

## we now form our Linear Model on Sex

In [99]:
from sklearn.linear_model import LinearRegression

In [100]:
model1 = LinearRegression()

In [156]:
final_sex_female.head()

age     bmi  children     region      charges  male
0   19  27.900         0  southwest  16884.92400     0
1   18  33.770         1  southeast   1725.55230     1
2   28  33.000         3  southeast   4449.46200     1
3   33  22.705         0  northwest  21984.47061     1
4   32  28.880         0  northwest   3866.85520     1

In [182]:
X=final_sex_female.drop(["region","charges"], axis =1)

In [171]:
X.head()

age     bmi  children  male
0   19  27.900         0     0
1   18  33.770         1     1
2   28  33.000         3     1
3   33  22.705         0     1
4   32  28.880         0     1

In [110]:
y = df.charges #target dataset

In [111]:
y.head()

0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: charges, dtype: float64

In [178]:
#X=X.values.reshape(-1,1)

In [183]:
model1.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [186]:
model1.coef_

array([ 241.26351116,  326.76149052,  533.16812969, 1321.71978238])

In [188]:
model1.score(X,y)

0.12306876681889367

In [196]:
final_region_merge.head()

age     sex     bmi  children smoker      charges  northeast  northwest  \
0   19  female  27.900         0    yes  16884.92400          0          0   
1   18    male  33.770         1     no   1725.55230          0          0   
2   28    male  33.000         3     no   4449.46200          0          0   
3   33    male  22.705         0     no  21984.47061          0          1   
4   32    male  28.880         0     no   3866.85520          0          1   

   southwest  
0          1  
1          0  
2          0  
3          0  
4          0

In [200]:
X1=final_region_merge.drop(["charges","sex","smoker"],axis =1)

In [201]:
X1.head()

age     bmi  children  northeast  northwest  southwest
0   19  27.900         0          0          0          1
1   18  33.770         1          0          0          0
2   28  33.000         3          0          0          0
3   33  22.705         0          0          1          0
4   32  28.880         0          0          1          0

In [202]:
y1 = final_region_merge["charges"]

In [203]:
y1.head()

0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: charges, dtype: float64

In [204]:
model2 = LinearRegression()

In [205]:
model2.fit(X1,y1)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [206]:
model2.score(X1,y1)

0.12349596404923369

In [221]:
dr = df.head()

In [222]:
dr.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [223]:
X2=dr.iloc[:,[0,2,3]]

In [224]:
X2.head()

age     bmi  children
0   19  27.900         0
1   18  33.770         1
2   28  33.000         3
3   33  22.705         0
4   32  28.880         0

In [218]:
X2=X2/X2.mean()

In [220]:
X2.head()

age       bmi  children
0  0.730769  0.953814      0.00
1  0.692308  1.154490      1.25
2  1.076923  1.128167      3.75
3  1.269231  0.776213      0.00
4  1.230769  0.987317      0.00

In [226]:
y2=dr.charges

In [227]:
y2

0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: charges, dtype: float64

In [228]:
model3 = LinearRegression()

In [229]:
model3.fit(X2,y2)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [231]:
model3.score(X2,y2)

0.9979509181412597

# using oneHotEncoding

In [235]:
from sklearn.preprocessing import LabelEncoder

In [236]:
le = LabelEncoder()

In [237]:
dfle = df

In [239]:
dfle.region=le.fit_transform(dfle.region)

In [241]:
dfle.head()

age     sex     bmi  children smoker  region      charges
0   19  female  27.900         0    yes       3  16884.92400
1   18    male  33.770         1     no       2   1725.55230
2   28    male  33.000         3     no       2   4449.46200
3   33    male  22.705         0     no       1  21984.47061
4   32    male  28.880         0     no       1   3866.85520

In [245]:
X4 = dfle.drop(["sex","smoker","charges"],axis=1).values

In [247]:
X4

array([[19.  , 27.9 ,  0.  ,  3.  ],
       [18.  , 33.77,  1.  ,  2.  ],
       [28.  , 33.  ,  3.  ,  2.  ],
       ...,
       [18.  , 36.85,  0.  ,  2.  ],
       [21.  , 25.8 ,  0.  ,  3.  ],
       [61.  , 29.07,  0.  ,  1.  ]])

In [248]:
y4 = dfle.charges

In [252]:
from sklearn.preprocessing import OneHotEncoder

In [254]:
ohe = OneHotEncoder(categorical_features=[0])

In [259]:
X4=ohe.fit_transform(X4).toarray()

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [260]:
X4

array([[ 0.  ,  1.  ,  0.  , ..., 27.9 ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , ..., 33.77,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , ..., 33.  ,  3.  ,  2.  ],
       ...,
       [ 1.  ,  0.  ,  0.  , ..., 36.85,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , ..., 25.8 ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  0.  , ..., 29.07,  0.  ,  1.  ]])

In [262]:
X4=X4[:,1:]

In [263]:
X4

array([[ 1.  ,  0.  ,  0.  , ..., 27.9 ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  0.  , ..., 33.77,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , ..., 33.  ,  3.  ,  2.  ],
       ...,
       [ 0.  ,  0.  ,  0.  , ..., 36.85,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , ..., 25.8 ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  0.  , ..., 29.07,  0.  ,  1.  ]])

In [268]:
model3.fit(X4,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [269]:
model3.score(X4,y)

0.15653028254155044